function ax1 = axis_definition


minlat = 55; maxlat = 84; nlat=maxlat-minlat;
minlon = -60; maxlon = 30; nlon=maxlon-minlon;

study_area = [linspace(minlon,maxlon,100)',maxlat*ones(100,1);...
    linspace(maxlon,minlon,100)',minlat*ones(100,1);...
    minlon,maxlat];




ax1 =axesm('lambertstd','MapLatLimit',[minlat-.01 maxlat+.01],'MapLonLimit',[minlon-.01 maxlon+.01],...
    'MLineLocation', 30, 'PLineLocation', 10,...
    'FontSize', 12, 'FontWeight','Bold','LabelFormat','none',...
    'LabelRotation','on','GLineWidth',.5,'GLineStyle','-','GAltitude',4,...
    'MLabelParallel',minlat-.01,'PLabelMeridian',minlon-.1);axis off; framem on; gridm off; mlabel on; plabel on;
